import type { SpeciesId } from "./types";

export type ShopCatId =
  | "food"
  | "treats"
  | "pharmacy"
  | "prevent"
  | "toys"
  | "gear"
  | "habitat"
  | "groom";

export interface ShopCategory {
  id: ShopCatId;
  label: string;
  blurb: string;
  subs: string[];
}

export interface Product {
  id: string;
  name: string;
  brand: string;
  price: number;
  compareAt?: number;
  rating: number;
  reviews: number;
  species: SpeciesId[] | "all";
  category: ShopCatId;
  sub: string;
  image: string;
  blurb: string;
  bullets: string[];
  autoship: boolean;
  rx: boolean;
  size: string;
}

export const SHOP_CATS: ShopCategory[] = [
  { id: "food", label: "Food", blurb: "Species-right bowls", subs: ["Kibble", "Wet", "Hay", "Pellets", "Frozen"] },
  { id: "treats", label: "Treats", blurb: "Training + forage", subs: ["Soft", "Dental", "Forage"] },
  { id: "pharmacy", label: "Pharmacy", blurb: "Rx + OTC, like Chewy", subs: ["Rx", "OTC", "Ear / eye"] },
  { id: "prevent", label: "Prevent", blurb: "Flea, tick, heartworm", subs: ["Chew", "Topical", "Collar"] },
  { id: "toys", label: "Toys", blurb: "Hunt, chew, forage", subs: ["Fetch", "Puzzle", "Wand"] },
  { id: "gear", label: "Gear", blurb: "Walks, wear, travel", subs: ["Leash", "Harness", "Carrier"] },
  { id: "habitat", label: "Habitat", blurb: "Tank, UVB, litter", subs: ["Litter", "Lighting", "Water"] },
  { id: "groom", label: "Groom", blurb: "Coat, nails, shed", subs: ["Bath", "Nails", "Tools"] },
];

export const PRODUCTS: Product[] = [
  {
    id: "orijen-dog",
    name: "Prairie kibble",
    brand: "Northbowl",
    price: 68,
    compareAt: 79,
    rating: 4.8,
    reviews: 2140,
    species: ["dog"],
    category: "food",
    sub: "Kibble",
    image: "/shop/kibble.jpg",
    blurb: "High-protein kibble sized for a 70 lb retriever. Transition over 7 days.",
    bullets: ["28 lb bag", "Chicken-first", "Fits Luna’s current mix"],
    autoship: true,
    rx: false,
    size: "28 lb",
  },
  {
    id: "joint-chew",
    name: "Daily joint chew",
    brand: "Stride",
    price: 32,
    rating: 4.6,
    reviews: 880,
    species: ["dog"],
    category: "pharmacy",
    sub: "OTC",
    image: "/shop/rx.jpg",
    blurb: "Glucosamine chew to keep on the breakfast plate during the kibble switch.",
    bullets: ["30 count", "Bacon", "Vet-counter formula"],
    autoship: true,
    rx: false,
    size: "30 ct",
  },
  {
    id: "nexgard",
    name: "Heartworm monthly",
    brand: "Spectra",
    price: 48,
    rating: 4.9,
    reviews: 5600,
    species: ["dog"],
    category: "prevent",
    sub: "Chew",
    image: "/shop/rx.jpg",
    blurb: "Matches Luna’s November due date. Rx on file with Dr. Jenkins.",
    bullets: ["6-pack", "Heartworm + flea", "Give with food"],
    autoship: true,
    rx: true,
    size: "6 mo",
  },
  {
    id: "pink-leash",
    name: "Soft leather leash",
    brand: "Harbor",
    price: 42,
    rating: 4.7,
    reviews: 312,
    species: ["dog"],
    category: "gear",
    sub: "Leash",
    image: "/shop/leash.jpg",
    blurb: "Matches the collar in her portrait. 5 ft for city sidewalks.",
    bullets: ["5 ft", "Brass hardware", "Hand-finished"],
    autoship: false,
    rx: false,
    size: "5 ft",
  },
  {
    id: "honey-ball",
    name: "River fetch ball",
    brand: "Kindling",
    price: 14,
    rating: 4.5,
    reviews: 190,
    species: ["dog"],
    category: "toys",
    sub: "Fetch",
    image: "/shop/ball.jpg",
    blurb: "Floats. Good for the limp-warm-up walks — keep throws short.",
    bullets: ["Floats", "Natural rubber", "M"],
    autoship: false,
    rx: false,
    size: "M",
  },
  {
    id: "miso-kibble",
    name: "Indoor cat recipe",
    brand: "Northbowl",
    price: 36,
    rating: 4.7,
    reviews: 1540,
    species: ["cat"],
    category: "food",
    sub: "Kibble",
    image: "/shop/catfood.jpg",
    blurb: "Calorie-controlled for a British Shorthair grazing all day.",
    bullets: ["6 lb", "Urinary care", "Measured scoop"],
    autoship: true,
    rx: false,
    size: "6 lb",
  },
  {
    id: "fountain",
    name: "Ceramic fountain",
    brand: "Rill",
    price: 54,
    rating: 4.8,
    reviews: 990,
    species: ["cat", "dog"],
    category: "habitat",
    sub: "Water",
    image: "/shop/fountain.jpg",
    blurb: "Miso already prefers moving water. Quiet pump, 2-cup bowl.",
    bullets: ["2 L", "Quiet", "Dishwasher basin"],
    autoship: false,
    rx: false,
    size: "2 L",
  },
  {
    id: "wand",
    name: "Dawn wand",
    brand: "Pounce",
    price: 12,
    rating: 4.6,
    reviews: 420,
    species: ["cat"],
    category: "toys",
    sub: "Wand",
    image: "/shop/leash.jpg",
    blurb: "Ten minutes of hunt before dinner cuts night zoomies.",
    bullets: ["Replaceable lure", "Carbon rod"],
    autoship: false,
    rx: false,
    size: "36 in",
  },
  {
    id: "litter",
    name: "Low-dust clump",
    brand: "Quietbox",
    price: 22,
    rating: 4.4,
    reviews: 2100,
    species: ["cat"],
    category: "habitat",
    sub: "Litter",
    image: "/shop/hay.jpg",
    blurb: "Track litter quality in Health — dust-free so you can read clumps.",
    bullets: ["18 lb", "Unscented"],
    autoship: true,
    rx: false,
    size: "18 lb",
  },
  {
    id: "pip-pellets",
    name: "Daily bird pellets",
    brand: "Perch",
    price: 18,
    rating: 4.7,
    reviews: 260,
    species: ["bird"],
    category: "food",
    sub: "Pellets",
    image: "/shop/pellets.jpg",
    blurb: "Pip is converting off seed. Weigh the dish, not just the bird.",
    bullets: ["2 lb", "Complete", "No sunflower"],
    autoship: true,
    rx: false,
    size: "2 lb",
  },
  {
    id: "cuttle",
    name: "Cuttle + mineral",
    brand: "Perch",
    price: 7,
    rating: 4.5,
    reviews: 80,
    species: ["bird"],
    category: "habitat",
    sub: "Water",
    image: "/shop/pellets.jpg",
    blurb: "Beak wear and calcium. Clip a new one at each molt check.",
    bullets: ["2 pack"],
    autoship: false,
    rx: false,
    size: "2 pk",
  },
  {
    id: "uvb",
    name: "T5 UVB tube 12%",
    brand: "Arc",
    price: 44,
    rating: 4.9,
    reviews: 640,
    species: ["reptile"],
    category: "habitat",
    sub: "Lighting",
    image: "/shop/uvb.jpg",
    blurb: "Ember’s bulb dates to January. Output dies before the light looks dead.",
    bullets: ["22 in", "12 month calendar"],
    autoship: false,
    rx: false,
    size: "22 in",
  },
  {
    id: "halogen",
    name: "Basking halogen",
    brand: "Arc",
    price: 16,
    rating: 4.6,
    reviews: 310,
    species: ["reptile"],
    category: "habitat",
    sub: "Lighting",
    image: "/shop/uvb.jpg",
    blurb: "Surface temp has been sliding to 97°F. Swap before the next feed.",
    bullets: ["75 W", "Flood"],
    autoship: false,
    rx: false,
    size: "75 W",
  },
  {
    id: "calcium",
    name: "Calcium + D3",
    brand: "Dust",
    price: 11,
    rating: 4.8,
    reviews: 500,
    species: ["reptile", "amphibian"],
    category: "pharmacy",
    sub: "OTC",
    image: "/shop/rx.jpg",
    blurb: "Dust feeders 3× a week. Pair with the new UVB, not instead of it.",
    bullets: ["4 oz"],
    autoship: true,
    rx: false,
    size: "4 oz",
  },
  {
    id: "prime",
    name: "Water conditioner",
    brand: "Clear",
    price: 13,
    rating: 4.9,
    reviews: 3200,
    species: ["fish", "amphibian"],
    category: "habitat",
    sub: "Water",
    image: "/shop/water.jpg",
    blurb: "Nori’s nitrate is 40 ppm. Condition every change — chloramine is invisible.",
    bullets: ["100 ml", "Detox ammonia"],
    autoship: true,
    rx: false,
    size: "100 ml",
  },
  {
    id: "betta-pellets",
    name: "Betta micro pellets",
    brand: "Clear",
    price: 9,
    rating: 4.6,
    reviews: 740,
    species: ["fish"],
    category: "food",
    sub: "Pellets",
    image: "/shop/pellets.jpg",
    blurb: "One pinch, twice a day. Overfeeding is what spikes nitrate.",
    bullets: ["30 g"],
    autoship: true,
    rx: false,
    size: "30 g",
  },
  {
    id: "test-kit",
    name: "Master test kit",
    brand: "Clear",
    price: 29,
    rating: 4.8,
    reviews: 1800,
    species: ["fish"],
    category: "habitat",
    sub: "Water",
    image: "/shop/water.jpg",
    blurb: "Strips lie. Liquid ammonia / nitrite / nitrate / pH — log them in Health.",
    bullets: ["800 tests"],
    autoship: false,
    rx: false,
    size: "Kit",
  },
  {
    id: "timothy",
    name: "Timothy hay brick",
    brand: "Meadow",
    price: 19,
    rating: 4.7,
    reviews: 910,
    species: ["rabbit", "small_mammal"],
    category: "food",
    sub: "Hay",
    image: "/shop/hay.jpg",
    blurb: "Clover’s diet is 80% this. Soft second-cut for all-day grazing.",
    bullets: ["5 lb", "2nd cut"],
    autoship: true,
    rx: false,
    size: "5 lb",
  },
  {
    id: "bunny-pellets",
    name: "Adult rabbit pellets",
    brand: "Meadow",
    price: 16,
    rating: 4.5,
    reviews: 430,
    species: ["rabbit"],
    category: "food",
    sub: "Pellets",
    image: "/shop/pellets.jpg",
    blurb: "Cap at 1/8 cup. More pellets, fewer cecotropes eaten.",
    bullets: ["4 lb", "Timothy-based"],
    autoship: true,
    rx: false,
    size: "4 lb",
  },
  {
    id: "vitc",
    name: "Vitamin C tabs",
    brand: "Cavy",
    price: 10,
    rating: 4.6,
    reviews: 210,
    species: ["small_mammal"],
    category: "pharmacy",
    sub: "OTC",
    image: "/shop/rx.jpg",
    blurb: "Guinea pigs cannot make vitamin C. Scurvy looks like laziness.",
    bullets: ["60 tabs"],
    autoship: true,
    rx: false,
    size: "60 ct",
  },
  {
    id: "shampoo",
    name: "Oat bath",
    brand: "Harbor",
    price: 18,
    rating: 4.4,
    reviews: 380,
    species: ["dog"],
    category: "groom",
    sub: "Bath",
    image: "/shop/water.jpg",
    blurb: "Luna’s next bath is mid-September. Oat for the spring itch leftover.",
    bullets: ["16 oz"],
    autoship: false,
    rx: false,
    size: "16 oz",
  },
  {
    id: "nail",
    name: "Quiet clippers",
    brand: "Harbor",
    price: 15,
    rating: 4.3,
    reviews: 270,
    species: ["dog", "cat", "rabbit"],
    category: "groom",
    sub: "Nails",
    image: "/shop/rx.jpg",
    blurb: "Dew claws were long last visit. Same tool, every species.",
    bullets: ["Safety guard"],
    autoship: false,
    rx: false,
    size: "One",
  },
  {
    id: "dental",
    name: "Dental sticks",
    brand: "Stride",
    price: 14,
    rating: 4.2,
    reviews: 660,
    species: ["dog"],
    category: "treats",
    sub: "Dental",
    image: "/shop/kibble.jpg",
    blurb: "Not a substitute for a cleaning — a daily mechanical wipe.",
    bullets: ["28 ct"],
    autoship: true,
    rx: false,
    size: "28 ct",
  },
  {
    id: "horse-salt",
    name: "Himalayan lick",
    brand: "Paddock",
    price: 21,
    rating: 4.6,
    reviews: 140,
    species: ["horse"],
    category: "food",
    sub: "Pellets",
    image: "/shop/hay.jpg",
    blurb: "Barn staple. Hang where the weight-tape lives.",
    bullets: ["4 lb"],
    autoship: false,
    rx: false,
    size: "4 lb",
  },
  {
    id: "ferret-food",
    name: "Carnivore kibble",
    brand: "Den",
    price: 28,
    rating: 4.5,
    reviews: 95,
    species: ["ferret"],
    category: "food",
    sub: "Kibble",
    image: "/shop/kibble.jpg",
    blurb: "High fat, high protein. Weigh weekly — winter gain is normal.",
    bullets: ["5 lb"],
    autoship: true,
    rx: false,
    size: "5 lb",
  },
];

export function productById(id: string) {
  return PRODUCTS.find((p) => p.id === id);
}

export function productsFor(species?: SpeciesId, cat?: ShopCatId, q?: string) {
  const needle = q?.trim().toLowerCase();
  return PRODUCTS.filter((p) => {
    if (cat && p.category !== cat) return false;
    if (species && p.species !== "all" && !p.species.includes(species)) return false;
    if (needle) {
      const hay = `${p.name} ${p.brand} ${p.sub} ${p.blurb}`.toLowerCase();
      if (!hay.includes(needle)) return false;
    }
    return true;
  });
}

export function money(n: number) {
  return `$${n.toFixed(n % 1 ? 2 : 0)}`;
}
