import type { SpeciesId, SpeciesProfile } from "./types";

export const SPECIES: Record<SpeciesId, SpeciesProfile> = {
  dog: {
    id: "dog",
    label: "Dog",
    plural: "Dogs",
    blurb: "Walks, weight, and parasite prevention tell most of the story.",
    problem:
      "Paper vaccine cards vanish, heartworm doses slip, and slow weight gain is missed until the vet scale.",
    solution:
      "A shared passport, monthly prevention clock, and a weight sparkline that flags a 5% swing.",
    defaultWeightUnit: "lb",
    careIntervalDays: { vet: 365, groom: 56, medsCheck: 30 },
    metrics: [
      {
        key: "weight",
        label: "Weight",
        unit: "lb",
        kind: "number",
        chart: true,
        hint: "Weekly at home, same scale.",
        why: "A 5% change in a month often precedes arthritis, thyroid, or diet issues — earlier than a yearly visit.",
      },
      {
        key: "height",
        label: "Height",
        unit: "in",
        kind: "number",
        chart: true,
        hint: "Withers to floor.",
        why: "Useful for growing pups and for tracking posture changes in seniors.",
      },
      {
        key: "activity",
        label: "Walks",
        unit: "min",
        kind: "number",
        chart: true,
        hint: "Total minutes today.",
        why: "Under-walked dogs present as 'behavior problems' that are really unmet exercise.",
      },
      {
        key: "appetite",
        label: "Appetite",
        unit: "/5",
        kind: "score",
        hint: "1 skipped — 5 cleaned bowl.",
        why: "Appetite drop is the earliest home signal for GI, dental, and systemic illness.",
      },
      {
        key: "stool",
        label: "Stool",
        unit: "/5",
        kind: "score",
        hint: "1 liquid — 5 firm.",
        why: "A 48-hour stool log is more useful to a vet than 'he seemed off.'",
      },
    ],
    vaccines: [
      { name: "Rabies", cadence: "1–3 years", required: true },
      { name: "DHPP", cadence: "1–3 years", required: true },
      { name: "Leptospirosis", cadence: "Yearly", required: false },
      { name: "Bordetella", cadence: "6–12 months", required: false },
      { name: "Canine influenza", cadence: "Yearly", required: false },
    ],
    redFlags: [
      "Straining or no stool for 24 hours",
      "Collapse, pale gums, or bloated hard belly",
      "Seizure or sudden blindness",
    ],
  },
  cat: {
    id: "cat",
    label: "Cat",
    plural: "Cats",
    blurb: "Weight, water, and the litter box — cats hide illness until late.",
    problem:
      "Most cats skip annual exams. Owners wait for 'obvious' sickness; by then kidney or dental disease is advanced.",
    solution:
      "Litter and water logs plus a hard yearly-vet reminder, because cats mask pain.",
    defaultWeightUnit: "lb",
    careIntervalDays: { vet: 365, groom: 90, medsCheck: 30 },
    metrics: [
      {
        key: "weight",
        label: "Weight",
        unit: "lb",
        kind: "number",
        chart: true,
        hint: "Baby scale works.",
        why: "Unexplained loss is the #1 home clue for hyperthyroidism, kidney disease, and diabetes.",
      },
      {
        key: "water",
        label: "Water",
        unit: "ml",
        kind: "number",
        chart: true,
        hint: "Fountain or measured bowl.",
        why: "Sudden thirst often flags diabetes or kidney disease weeks before bloodwork.",
      },
      {
        key: "litter",
        label: "Litter",
        unit: "/5",
        kind: "score",
        hint: "1 straining — 5 normal.",
        why: "A blocked male cat is a same-day emergency. Frequency changes are the warning.",
      },
      {
        key: "vomiting",
        label: "Vomiting",
        unit: "x",
        kind: "number",
        hint: "Count today.",
        why: "'Hairballs' that happen weekly are not normal — they can be IBD or food intolerance.",
      },
      {
        key: "activity",
        label: "Play",
        unit: "min",
        kind: "number",
        chart: true,
        hint: "Wand or chase time.",
        why: "Indoor cats under-hunt. Short play sessions cut obesity and urine marking.",
      },
    ],
    vaccines: [
      { name: "Rabies", cadence: "1–3 years", required: true },
      { name: "FVRCP", cadence: "1–3 years", required: true },
      { name: "FeLV", cadence: "Yearly if outdoor", required: false },
    ],
    redFlags: [
      "Straining in the box with no urine",
      "Open-mouth breathing or blue gums",
      "Sudden collapse or inability to walk",
    ],
  },
  bird: {
    id: "bird",
    label: "Bird",
    plural: "Birds",
    blurb: "Daily weight in grams is the vital sign. A 10% drop is an emergency.",
    problem:
      "Birds hide illness until they are crashing. Seed-only diets cause liver disease that owners never see coming.",
    solution:
      "A gram scale every morning, droppings photos, and a pellet/fresh-food log — not a yearly weigh-in.",
    defaultWeightUnit: "g",
    careIntervalDays: { vet: 365, groom: 60 },
    metrics: [
      {
        key: "weight",
        label: "Weight",
        unit: "g",
        kind: "number",
        chart: true,
        hint: "Same perch, same hour.",
        why: "A 5–10% drop in 48 hours is often the only warning before a bird is too weak to perch.",
      },
      {
        key: "droppings",
        label: "Droppings",
        unit: "/5",
        kind: "score",
        hint: "1 watery — 5 formed.",
        why: "Color and volume changes flag liver, kidney, and infection faster than behavior.",
      },
      {
        key: "appetite",
        label: "Appetite",
        unit: "/5",
        kind: "score",
        hint: "Pellets vs seed.",
        why: "Seed junkies look 'fine' while fatty liver builds. Track pellets eaten, not just bowl empty.",
      },
      {
        key: "vocal",
        label: "Voice",
        unit: "/5",
        kind: "score",
        hint: "1 silent — 5 usual.",
        why: "A quiet bird is a sick bird until proven otherwise.",
      },
      {
        key: "molt",
        label: "Molt",
        unit: "/5",
        kind: "score",
        hint: "Feather condition.",
        why: "Stuck pins and bald patches can be nutrition, mites, or stress — not just 'shedding.'",
      },
    ],
    vaccines: [
      { name: "Polyomavirus (if recommended)", cadence: "As advised", required: false },
    ],
    redFlags: [
      "Fluffed, tail-bobbing, or sitting on cage floor",
      "Bleeding (birds cannot clot well)",
      "Overnight 10% weight loss",
    ],
  },
  rabbit: {
    id: "rabbit",
    label: "Rabbit",
    plural: "Rabbits",
    blurb: "Hay, fecal pellets, and gut sounds — GI stasis kills quietly.",
    problem:
      "Owners treat rabbits like hamsters. A quiet afternoon can be GI stasis, which is a same-day emergency.",
    solution:
      "Hourly hay + pellet counts when off-feed, and a 4-hour rule: no poops means call an exotic vet.",
    defaultWeightUnit: "lb",
    careIntervalDays: { vet: 365, groom: 30 },
    metrics: [
      {
        key: "weight",
        label: "Weight",
        unit: "lb",
        kind: "number",
        chart: true,
        hint: "Kitchen scale + carrier.",
        why: "Dental disease and gut slowdown show first as quiet weight loss.",
      },
      {
        key: "hay",
        label: "Hay",
        unit: "/5",
        kind: "score",
        hint: "Unlimited timothy.",
        why: "Hay is 80% of the diet. Low hay = overgrown molars and stasis risk.",
      },
      {
        key: "fecals",
        label: "Pellets",
        unit: "x",
        kind: "number",
        chart: true,
        hint: "Count a typical hour.",
        why: "Fewer, smaller, or chained pellets are the earliest GI stasis sign.",
      },
      {
        key: "cecotropes",
        label: "Cecotropes",
        unit: "/5",
        kind: "score",
        hint: "Should be eaten, not left.",
        why: "Uneaten cecotropes mean pain, obesity, or diet too rich in pellets.",
      },
      {
        key: "teeth",
        label: "Teeth",
        unit: "/5",
        kind: "score",
        hint: "Incisors even, eating hay.",
        why: "Rabbit teeth grow continuously. Drooling or dropping food is dental until proven otherwise.",
      },
    ],
    vaccines: [
      { name: "RHDV2", cadence: "Yearly", required: true },
      { name: "Myxomatosis (region)", cadence: "Yearly", required: false },
    ],
    redFlags: [
      "No fecal pellets for 4 hours + hunched",
      "Loud teeth grinding (pain)",
      "Head tilt or rolling",
    ],
  },
  reptile: {
    id: "reptile",
    label: "Reptile",
    plural: "Reptiles",
    blurb: "The enclosure is the medicine — heat, UVB, humidity, then food.",
    problem:
      "Most 'mystery illness' in beardies and geckos is a failed heat gradient or expired UVB bulb.",
    solution:
      "Log hot/cool spots and UVB-bulb age. Feeding is weekly, not daily — track sheds and appetite against temps.",
    defaultWeightUnit: "g",
    careIntervalDays: { vet: 365 },
    metrics: [
      {
        key: "weight",
        label: "Weight",
        unit: "g",
        kind: "number",
        chart: true,
        hint: "Pre-feed, weekly.",
        why: "Reptiles lose weight slowly. A trend line beats a single 'he looks fine.'",
      },
      {
        key: "hot_spot",
        label: "Basking",
        unit: "°F",
        kind: "number",
        chart: true,
        hint: "Surface temp, not air.",
        target: "Species-specific",
        why: "Without a true basking surface they cannot digest. Undigested food becomes impaction.",
      },
      {
        key: "cool_spot",
        label: "Cool side",
        unit: "°F",
        kind: "number",
        hint: "They must be able to escape heat.",
        why: "A gradient is how reptiles self-regulate. One temp for the whole tank cooks or chills them.",
      },
      {
        key: "humidity",
        label: "Humidity",
        unit: "%",
        kind: "number",
        chart: true,
        hint: "Probe at hide height.",
        why: "Stuck sheds and respiratory infections are humidity problems first.",
      },
      {
        key: "uvb_hours",
        label: "UVB",
        unit: "hr",
        kind: "number",
        hint: "Replace bulbs on a calendar.",
        why: "UVB output dies long before the light looks dead. Metabolic bone disease starts here.",
      },
      {
        key: "shed",
        label: "Shed",
        unit: "/5",
        kind: "score",
        hint: "1 stuck — 5 complete.",
        why: "Toe-tip and eye-cap sheds left on cause loss of digits and vision.",
      },
    ],
    vaccines: [],
    redFlags: [
      "Open-mouth breathing or bubbles",
      "Unable to use hind legs",
      "Prolapse or 48h with no stool after a feed",
    ],
  },
  fish: {
    id: "fish",
    label: "Fish",
    plural: "Fish",
    blurb: "Test the water, not the fish. Chemistry is the health record.",
    problem:
      "People medicate a sick betta while ammonia is burning the gills. The tank is the patient.",
    solution:
      "A weekly strip or kit log for ammonia, nitrite, nitrate, pH, and temp — plus water-change %.",
    defaultWeightUnit: "g",
    careIntervalDays: { vet: 0 },
    metrics: [
      {
        key: "temp",
        label: "Temp",
        unit: "°F",
        kind: "number",
        chart: true,
        hint: "Heater + thermometer.",
        why: "A 4° swing overnight is more dangerous than most 'mystery' diseases.",
      },
      {
        key: "ammonia",
        label: "Ammonia",
        unit: "ppm",
        kind: "number",
        chart: true,
        target: "0",
        hint: "Must read zero.",
        why: "Any ammonia above 0 burns gills. This is the number new tanks get wrong.",
      },
      {
        key: "nitrite",
        label: "Nitrite",
        unit: "ppm",
        kind: "number",
        target: "0",
        hint: "Must read zero.",
        why: "Nitrite blocks oxygen in the blood. A cycled tank should read zero.",
      },
      {
        key: "nitrate",
        label: "Nitrate",
        unit: "ppm",
        kind: "number",
        chart: true,
        hint: "Water-change driver.",
        why: "Rising nitrate means it is time to change water — not add more fish.",
      },
      {
        key: "ph",
        label: "pH",
        unit: "",
        kind: "number",
        chart: true,
        hint: "Stability > perfect number.",
        why: "Chasing pH with chemicals shocks fish. Track drift, don't yo-yo.",
      },
      {
        key: "change",
        label: "Water change",
        unit: "%",
        kind: "number",
        hint: "Weekly typical.",
        why: "The cheapest medicine in the hobby. Log it so you notice when you skipped.",
      },
    ],
    vaccines: [],
    redFlags: [
      "Gasping at the surface",
      "Clamped fins + flashing on décor",
      "Ammonia or nitrite above 0",
    ],
  },
  horse: {
    id: "horse",
    label: "Horse",
    plural: "Horses",
    blurb: "Feet, feed, and fecal egg counts — barn records save colic calls.",
    problem:
      "Vaccine, farrier, and deworm logs live in three binders. A new barn manager inherits chaos.",
    solution:
      "One passport: farrier cycle, dental float, Coggins, and a weight-tape trend.",
    defaultWeightUnit: "lb",
    careIntervalDays: { vet: 180, groom: 1, medsCheck: 90 },
    metrics: [
      {
        key: "weight",
        label: "Weight tape",
        unit: "lb",
        kind: "number",
        chart: true,
        hint: "Same tape, same handler.",
        why: "BCS + tape catch metabolic syndrome before laminitis.",
      },
      {
        key: "bcs",
        label: "Body condition",
        unit: "/9",
        kind: "score",
        hint: "Henneke 1–9.",
        why: "Cresty necks and fat pads are metabolic red flags even at a 'normal' weight.",
      },
      {
        key: "hoof",
        label: "Hoof",
        unit: "/5",
        kind: "score",
        hint: "After each farrier.",
        why: "No hoof, no horse. Track abscess, thrush, and cycle length.",
      },
      {
        key: "manure",
        label: "Manure",
        unit: "/5",
        kind: "score",
        hint: "1 dry / mucus — 5 normal.",
        why: "Colic often starts as a manure-output change hours earlier.",
      },
    ],
    vaccines: [
      { name: "EEE / WEE / tetanus", cadence: "Yearly", required: true },
      { name: "Rabies", cadence: "Yearly", required: true },
      { name: "West Nile", cadence: "Yearly", required: true },
      { name: "Flu / rhino", cadence: "6–12 months", required: false },
    ],
    redFlags: [
      "Pawing, rolling, no gut sounds",
      "Sudden lameness or heat in a hoof",
      "Unable to rise",
    ],
  },
  small_mammal: {
    id: "small_mammal",
    label: "Small mammal",
    plural: "Small mammals",
    blurb: "Grams matter. Guinea pigs need vitamin C; hamsters hide tumors.",
    problem:
      "A 20g loss on a 900g guinea pig is huge — kitchen scales are rarely used until it is late.",
    solution:
      "Weekly grams, vitamin C for cavies, and a hay-first diet like rabbits.",
    defaultWeightUnit: "g",
    careIntervalDays: { vet: 365, groom: 30 },
    metrics: [
      {
        key: "weight",
        label: "Weight",
        unit: "g",
        kind: "number",
        chart: true,
        hint: "Weekly, pre-treat.",
        why: "These animals crash fast. A 5% drop is a same-week vet visit.",
      },
      {
        key: "vitc",
        label: "Vitamin C",
        unit: "/5",
        kind: "score",
        hint: "Guinea pigs only.",
        why: "Cavies cannot make vitamin C. Scurvy looks like 'laziness.'",
      },
      {
        key: "hay",
        label: "Hay",
        unit: "/5",
        kind: "score",
        hint: "Always available.",
        why: "Dental and gut health in guinea pigs and chinchillas is hay, not pellets.",
      },
      {
        key: "activity",
        label: "Activity",
        unit: "/5",
        kind: "score",
        hint: "Wheel, popcorning, explore.",
        why: "A still hamster in daylight can be normal — a still guinea pig is not.",
      },
    ],
    vaccines: [],
    redFlags: [
      "Not eating for 8 hours",
      "Labored breathing",
      "Blood in urine (especially guinea pigs)",
    ],
  },
  ferret: {
    id: "ferret",
    label: "Ferret",
    plural: "Ferrets",
    blurb: "Insulinoma and adrenal disease are common — weight and sleep tell.",
    problem:
      "Owners chalk up lethargy to 'getting old' at age four. That's often insulinoma.",
    solution:
      "Weekly weight, a note on staring/drooling after a nap, and canine-distemper vaccine on file.",
    defaultWeightUnit: "g",
    careIntervalDays: { vet: 180 },
    metrics: [
      {
        key: "weight",
        label: "Weight",
        unit: "g",
        kind: "number",
        chart: true,
        hint: "Seasonal swing is normal.",
        why: "Winter gain is expected. Steady loss or extreme thinness is not.",
      },
      {
        key: "energy",
        label: "Energy",
        unit: "/5",
        kind: "score",
        hint: "After waking.",
        why: "Weakness after a nap plus glassy stare is classic low blood sugar.",
      },
      {
        key: "itch",
        label: "Itch / hair",
        unit: "/5",
        kind: "score",
        hint: "Tail and flanks.",
        why: "Rat-tail and itch in a desexed ferret often means adrenal disease.",
      },
    ],
    vaccines: [
      { name: "Canine distemper (ferret-safe)", cadence: "Yearly", required: true },
      { name: "Rabies", cadence: "Yearly", required: true },
    ],
    redFlags: [
      "Collapse, drooling, or glassy stare after sleep",
      "Straining to urinate (males, adrenal)",
      "Vomiting that will not stop",
    ],
  },
  amphibian: {
    id: "amphibian",
    label: "Amphibian",
    plural: "Amphibians",
    blurb: "Skin is the lung. Water quality and humidity are the chart.",
    problem:
      "Handling with dry hands and tap water with chloramine quietly wrecks frogs.",
    solution:
      "Dechlorinated water log, humidity, and a 'hands-off unless needed' rule.",
    defaultWeightUnit: "g",
    careIntervalDays: { vet: 365 },
    metrics: [
      {
        key: "weight",
        label: "Weight",
        unit: "g",
        kind: "number",
        chart: true,
        hint: "In a cup, weekly.",
        why: "Weight is the only reliable body-condition check — they puff up when stressed.",
      },
      {
        key: "humidity",
        label: "Humidity",
        unit: "%",
        kind: "number",
        chart: true,
        hint: "Species range.",
        why: "Drying skin is a respiratory emergency for many frogs.",
      },
      {
        key: "water",
        label: "Water quality",
        unit: "/5",
        kind: "score",
        hint: "Dechlorinated, clean.",
        why: "Chlorine and ammonia absorb through skin. The bowl is the bloodstream.",
      },
    ],
    vaccines: [],
    redFlags: [
      "Red legs or open sores",
      "Unable to dive / floating oddly",
      "Cloudy eyes and no eating",
    ],
  },
  other: {
    id: "other",
    label: "Other",
    plural: "Other pets",
    blurb: "Start with weight, appetite, and a species note — then customize.",
    problem:
      "One-size trackers force dog fields onto a tarantula or a goat.",
    solution:
      "Pick the closest cousin species, then add the metrics you actually measure.",
    defaultWeightUnit: "g",
    careIntervalDays: { vet: 365 },
    metrics: [
      {
        key: "weight",
        label: "Weight",
        unit: "g",
        kind: "number",
        chart: true,
        hint: "Whatever scale you have.",
        why: "Across species, a trend in body mass is the most portable vital sign.",
      },
      {
        key: "appetite",
        label: "Appetite",
        unit: "/5",
        kind: "score",
        hint: "Compared to their normal.",
        why: "Owners notice 'off' first as food left behind.",
      },
      {
        key: "energy",
        label: "Energy",
        unit: "/5",
        kind: "score",
        hint: "Compared to their normal.",
        why: "A one-line energy score makes a vet timeline actually useful.",
      },
    ],
    vaccines: [],
    redFlags: ["Sudden inability to stand", "Uncontrolled bleeding", "Not eating plus hiding"],
  },
};

export const SPECIES_LIST = Object.values(SPECIES);

export function speciesOf(id: SpeciesId) {
  return SPECIES[id] ?? SPECIES.other;
}

export function metricDef(species: SpeciesId, key: string) {
  return speciesOf(species).metrics.find((m) => m.key === key);
}
