/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AidRouteImport } from './routes/aid'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as CareRouteImport } from './routes/care'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CoverRouteImport } from './routes/cover'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as GuideRouteImport } from './routes/guide'
import { Route as HandoffRouteImport } from './routes/handoff'
import { Route as HealthRouteImport } from './routes/health'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MoreRouteImport } from './routes/more'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SpendRouteImport } from './routes/spend'
import { Route as TagRouteImport } from './routes/tag'
import { Route as TrainRouteImport } from './routes/train'
import { Route as TravelRouteImport } from './routes/travel'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ShopCCatIdRouteImport } from './routes/shop.c.$catId'
import { Route as ShopPIdRouteImport } from './routes/shop.p.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AidRoute = AidRouteImport.update({
  id: '/aid',
  path: '/aid',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const CareRoute = CareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CoverRoute = CoverRouteImport.update({
  id: '/cover',
  path: '/cover',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideRoute = GuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffRoute = HandoffRouteImport.update({
  id: '/handoff',
  path: '/handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SpendRoute = SpendRouteImport.update({
  id: '/spend',
  path: '/spend',
  getParentRoute: () => rootRouteImport,
} as any)
const TagRoute = TagRouteImport.update({
  id: '/tag',
  path: '/tag',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainRoute = TrainRouteImport.update({
  id: '/train',
  path: '/train',
  getParentRoute: () => rootRouteImport,
} as any)
const TravelRoute = TravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShopRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopCCatIdRoute = ShopCCatIdRouteImport.update({
  id: '/c/$catId',
  path: '/c/$catId',
  getParentRoute: () => ShopRoute,
} as any)
const ShopPIdRoute = ShopPIdRouteImport.update({
  id: '/p/$id',
  path: '/p/$id',
  getParentRoute: () => ShopRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aid': typeof AidRoute
  '/album': typeof AlbumRoute
  '/calendar': typeof CalendarRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/cover': typeof CoverRoute
  '/documents': typeof DocumentsRoute
  '/guide': typeof GuideRoute
  '/handoff': typeof HandoffRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/pets': typeof PetsRoute
  '/shop': typeof ShopRouteWithChildren
  '/spend': typeof SpendRoute
  '/tag': typeof TagRoute
  '/train': typeof TrainRoute
  '/travel': typeof TravelRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/shop/c/$catId': typeof ShopCCatIdRoute
  '/shop/p/$id': typeof ShopPIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aid': typeof AidRoute
  '/album': typeof AlbumRoute
  '/calendar': typeof CalendarRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/cover': typeof CoverRoute
  '/documents': typeof DocumentsRoute
  '/guide': typeof GuideRoute
  '/handoff': typeof HandoffRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/pets': typeof PetsRoute
  '/spend': typeof SpendRoute
  '/tag': typeof TagRoute
  '/train': typeof TrainRoute
  '/travel': typeof TravelRoute
  '/shop': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/shop/c/$catId': typeof ShopCCatIdRoute
  '/shop/p/$id': typeof ShopPIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aid': typeof AidRoute
  '/album': typeof AlbumRoute
  '/calendar': typeof CalendarRoute
  '/care': typeof CareRoute
  '/cart': typeof CartRoute
  '/cover': typeof CoverRoute
  '/documents': typeof DocumentsRoute
  '/guide': typeof GuideRoute
  '/handoff': typeof HandoffRoute
  '/health': typeof HealthRoute
  '/inbox': typeof InboxRoute
  '/journal': typeof JournalRoute
  '/login': typeof LoginRoute
  '/more': typeof MoreRoute
  '/pets': typeof PetsRoute
  '/shop': typeof ShopRouteWithChildren
  '/spend': typeof SpendRoute
  '/tag': typeof TagRoute
  '/train': typeof TrainRoute
  '/travel': typeof TravelRoute
  '/shop/': typeof ShopIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/shop/c/$catId': typeof ShopCCatIdRoute
  '/shop/p/$id': typeof ShopPIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aid'
    | '/album'
    | '/calendar'
    | '/care'
    | '/cart'
    | '/cover'
    | '/documents'
    | '/guide'
    | '/handoff'
    | '/health'
    | '/inbox'
    | '/journal'
    | '/login'
    | '/more'
    | '/pets'
    | '/shop'
    | '/spend'
    | '/tag'
    | '/train'
    | '/travel'
    | '/shop/'
    | '/api/auth/$'
    | '/shop/c/$catId'
    | '/shop/p/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aid'
    | '/album'
    | '/calendar'
    | '/care'
    | '/cart'
    | '/cover'
    | '/documents'
    | '/guide'
    | '/handoff'
    | '/health'
    | '/inbox'
    | '/journal'
    | '/login'
    | '/more'
    | '/pets'
    | '/spend'
    | '/tag'
    | '/train'
    | '/travel'
    | '/shop'
    | '/api/auth/$'
    | '/shop/c/$catId'
    | '/shop/p/$id'
  id:
    | '__root__'
    | '/'
    | '/aid'
    | '/album'
    | '/calendar'
    | '/care'
    | '/cart'
    | '/cover'
    | '/documents'
    | '/guide'
    | '/handoff'
    | '/health'
    | '/inbox'
    | '/journal'
    | '/login'
    | '/more'
    | '/pets'
    | '/shop'
    | '/spend'
    | '/tag'
    | '/train'
    | '/travel'
    | '/shop/'
    | '/api/auth/$'
    | '/shop/c/$catId'
    | '/shop/p/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AidRoute: typeof AidRoute
  AlbumRoute: typeof AlbumRoute
  CalendarRoute: typeof CalendarRoute
  CareRoute: typeof CareRoute
  CartRoute: typeof CartRoute
  CoverRoute: typeof CoverRoute
  DocumentsRoute: typeof DocumentsRoute
  GuideRoute: typeof GuideRoute
  HandoffRoute: typeof HandoffRoute
  HealthRoute: typeof HealthRoute
  InboxRoute: typeof InboxRoute
  JournalRoute: typeof JournalRoute
  LoginRoute: typeof LoginRoute
  MoreRoute: typeof MoreRoute
  PetsRoute: typeof PetsRoute
  ShopRoute: typeof ShopRouteWithChildren
  SpendRoute: typeof SpendRoute
  TagRoute: typeof TagRoute
  TrainRoute: typeof TrainRoute
  TravelRoute: typeof TravelRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aid': {
      id: '/aid'
      path: '/aid'
      fullPath: '/aid'
      preLoaderRoute: typeof AidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care': {
      id: '/care'
      path: '/care'
      fullPath: '/care'
      preLoaderRoute: typeof CareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cover': {
      id: '/cover'
      path: '/cover'
      fullPath: '/cover'
      preLoaderRoute: typeof CoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide': {
      id: '/guide'
      path: '/guide'
      fullPath: '/guide'
      preLoaderRoute: typeof GuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff': {
      id: '/handoff'
      path: '/handoff'
      fullPath: '/handoff'
      preLoaderRoute: typeof HandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spend': {
      id: '/spend'
      path: '/spend'
      fullPath: '/spend'
      preLoaderRoute: typeof SpendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tag': {
      id: '/tag'
      path: '/tag'
      fullPath: '/tag'
      preLoaderRoute: typeof TagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/train': {
      id: '/train'
      path: '/train'
      fullPath: '/train'
      preLoaderRoute: typeof TrainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/travel': {
      id: '/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof TravelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/c/$catId': {
      id: '/shop/c/$catId'
      path: '/c/$catId'
      fullPath: '/shop/c/$catId'
      preLoaderRoute: typeof ShopCCatIdRouteImport
      parentRoute: typeof ShopRoute
    }
    '/shop/p/$id': {
      id: '/shop/p/$id'
      path: '/p/$id'
      fullPath: '/shop/p/$id'
      preLoaderRoute: typeof ShopPIdRouteImport
      parentRoute: typeof ShopRoute
    }
  }
}

interface ShopRouteChildren {
  ShopIndexRoute: typeof ShopIndexRoute
  ShopCCatIdRoute: typeof ShopCCatIdRoute
  ShopPIdRoute: typeof ShopPIdRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopIndexRoute: ShopIndexRoute,
  ShopCCatIdRoute: ShopCCatIdRoute,
  ShopPIdRoute: ShopPIdRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AidRoute: AidRoute,
  AlbumRoute: AlbumRoute,
  CalendarRoute: CalendarRoute,
  CareRoute: CareRoute,
  CartRoute: CartRoute,
  CoverRoute: CoverRoute,
  DocumentsRoute: DocumentsRoute,
  GuideRoute: GuideRoute,
  HandoffRoute: HandoffRoute,
  HealthRoute: HealthRoute,
  InboxRoute: InboxRoute,
  JournalRoute: JournalRoute,
  LoginRoute: LoginRoute,
  MoreRoute: MoreRoute,
  PetsRoute: PetsRoute,
  ShopRoute: ShopRouteWithChildren,
  SpendRoute: SpendRoute,
  TagRoute: TagRoute,
  TrainRoute: TrainRoute,
  TravelRoute: TravelRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
